"""The Python twin of ``test/validate.spec.ts`` - the F0.4 semantic-validator acceptance test.

WHAT IS BEING GRADED AGAINST WHAT.

* ``conformance/validator-clean.json`` is a semantically perfect PaperIR document, GENERATED by
  ``conformance/generate-validator-clean.py`` so that ``block_id``, ``text_normalised`` and
  ``content_hash`` are real rather than invented.
* ``conformance/validator-cases.json`` is HAND-WRITTEN: 68 patches of that document, each with the
  exact ordered list of ``(rule, severity, path)`` triples the validator must produce.
  ``test/validate.spec.ts`` asserts the same file. Neither language is the other's oracle; both are
  graded against one hand-written recording.
* ``test/cases/001-worked-example.json`` - DESIGN.md section 8's documented worked example - is
  validated too, and it FAILS three rules. That is a finding about the document, not about the
  validator, and it is asserted exactly so neither can drift silently.

MESSAGES ARE NOT PART OF THE CROSS-LANGUAGE CONTRACT (they interpolate numbers, and ``str(1.0)``
is ``"1.0"`` here while ``String(1.0)`` is ``"1"`` in JS). The triples are.

Every mutated document is re-parsed through ``Paper.model_validate`` first, which is what makes the
cases file's central claim checkable: these are all defects the JSON Schema CANNOT see.
"""

from __future__ import annotations

import copy
import json
import unicodedata
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any

import pytest
from papertree_document_ir.generated.models import Paper, Repair
from papertree_document_ir.identity import (
    BlockIdInput,
    content_hash,
    normalise_text,
)
from papertree_document_ir.identity import block_id as recompute_block_id
from papertree_document_ir.validate import (
    SEMANTIC_RULES,
    Diagnostic,
    SemanticValidationError,
    ValidateOptions,
    assert_valid_paper,
    format_diagnostics,
    validate_paper,
)

PKG = Path(__file__).resolve().parents[2]
CLEAN: dict[str, Any] = json.loads(
    (PKG / "conformance" / "validator-clean.json").read_text(encoding="utf-8")
)["document"]
CASES: dict[str, Any] = json.loads(
    (PKG / "conformance" / "validator-cases.json").read_text(encoding="utf-8")
)
WORKED_EXAMPLE: dict[str, Any] = json.loads(
    (PKG / "test" / "cases" / "001-worked-example.json").read_text(encoding="utf-8")
)["document"]


# ─── THE PATCHER (see validator-cases.json "patch_ops") ─────────────────────────────────────


def read_path(root: Any, path: str) -> Any:
    node = root
    if path == "":
        return node
    for segment in path.split("/"):
        node = node[int(segment)] if isinstance(node, list) else node[segment]
    return node


def resolve_value(value: Any) -> Any:
    """A string value beginning with ``@`` is a path read out of the UNMUTATED clean document."""
    if isinstance(value, str):
        return copy.deepcopy(read_path(CLEAN, value[1:])) if value.startswith("@") else value
    if isinstance(value, list):
        return [resolve_value(v) for v in value]
    if isinstance(value, dict):
        return {k: resolve_value(v) for k, v in value.items()}
    return value


def apply_ops(document: dict[str, Any], ops: Sequence[dict[str, Any]]) -> dict[str, Any]:
    for op in ops:
        if "set" in op or "delete" in op:
            path = str(op.get("set", op.get("delete"))).split("/")
            parent = read_path(document, "/".join(path[:-1]))
            last = path[-1]
            if "delete" in op:
                if isinstance(parent, list):
                    del parent[int(last)]
                else:
                    del parent[last]
            elif isinstance(parent, list):
                parent[int(last)] = resolve_value(op["value"])
            else:
                parent[last] = resolve_value(op["value"])
        elif "append" in op:
            read_path(document, op["append"]).append(resolve_value(op["value"]))
        else:
            raise AssertionError(f"unknown patch op {op!r}")
    return document


def options_for(raw: dict[str, Any] | None) -> ValidateOptions:
    if raw is None:
        return ValidateOptions()
    return ValidateOptions(
        disabled_rules=frozenset(raw.get("disabled_rules", ())),
        out_of_crop_box_error_fraction=raw.get("out_of_crop_box_error_fraction", 0.05),
        min_page_coverage_fraction=raw.get("min_page_coverage_fraction", 0.01),
    )


def triples(diagnostics: Sequence[Diagnostic]) -> list[dict[str, str]]:
    return [{"rule": d.rule, "severity": d.severity, "path": d.path} for d in diagnostics]


def schema_valid(document: dict[str, Any]) -> Paper:
    """Every mutated document must still satisfy the schema - that is the file's whole claim."""
    return Paper.model_validate(document)


def clean_paper() -> Paper:
    return schema_valid(copy.deepcopy(CLEAN))


def mutated(*ops: dict[str, Any]) -> Paper:
    return schema_valid(apply_ops(copy.deepcopy(CLEAN), ops))


def bypass(mutate: Callable[[Paper], None]) -> Paper:
    """A Paper mutated AFTER validation - the only honest way to reach a rule the schema forbids.

    ``model_construct`` would leave ``blocks`` as raw dicts and test nothing; assigning to an
    already-validated model is exactly the caller this rule class exists for, because Pydantic does
    not re-validate on assignment.
    """
    paper = clean_paper()
    mutate(paper)
    return paper


# ─── THE CONFORMANCE CASES ──────────────────────────────────────────────────────────────────


CASE_LIST: list[dict[str, Any]] = CASES["cases"]


@pytest.mark.parametrize("case", CASE_LIST, ids=[c["name"] for c in CASE_LIST])
def test_conformance_case(case: dict[str, Any]) -> None:
    document = apply_ops(copy.deepcopy(CLEAN), case["ops"])
    paper = schema_valid(document)
    report = validate_paper(paper, options_for(case.get("options")))
    assert triples(report.diagnostics) == case["expect"], format_diagnostics(report.diagnostics)
    assert report.ok == (len(report.errors) == 0)
    assert len(report.errors) + len(report.warnings) == len(report.diagnostics)


def test_every_rule_is_exercised_by_some_case() -> None:
    exercised = {e["rule"] for case in CASE_LIST for e in case["expect"]}
    # The rules a schema-valid document CANNOT reach are asserted separately, behind the schema's
    # back - see the "unreachable through the JSON Schema" tests below.
    exercised |= {"G5", "R30"}
    missing = [r.id for r in SEMANTIC_RULES if r.id not in exercised]
    assert missing == [], f"rules with no test: {missing}"


def test_the_cases_file_is_the_one_the_typescript_twin_reads() -> None:
    assert len(CASE_LIST) == 68
    assert len({c["name"] for c in CASE_LIST}) == len(CASE_LIST)
    assert CASES["clean"] == "validator-clean.json"


# ─── THE CLEAN DOCUMENT ─────────────────────────────────────────────────────────────────────


def test_the_clean_document_is_semantically_silent() -> None:
    report = validate_paper(clean_paper())
    assert format_diagnostics(report.diagnostics) == ""
    assert report.ok is True


def test_the_clean_document_carries_real_recomputed_block_ids() -> None:
    ids = [b["block_id"] for b in CLEAN["blocks"]]
    assert len(ids) == 12
    assert len(set(ids)) == 12
    for block_id in ids:
        assert len(block_id) == 20 and block_id.startswith("blk_")


def test_validation_is_deterministic_across_repeated_runs() -> None:
    paper = clean_paper()
    broken = mutated(
        {"set": "blocks/0/bbox/2", "value": 559},
        {"set": "blocks/1/order", "value": 2},
        {"set": "confidence/overall", "value": None},
    )
    first = triples(validate_paper(broken).diagnostics)
    for _ in range(8):
        assert validate_paper(paper).diagnostics == ()
        assert triples(validate_paper(broken).diagnostics) == first
    assert len(first) == 4


def test_diagnostics_come_out_in_semantic_rules_order() -> None:
    order = {rule.id: index for index, rule in enumerate(SEMANTIC_RULES)}
    report = validate_paper(
        mutated(
            {"set": "blocks/0/bbox/2", "value": 559},
            {"set": "confidence/overall", "value": None},
            {"set": "references/0/venue", "value": "NeurIPS"},
            {"set": "pages/0/width", "value": 600},
        )
    )
    indices = [order[d.rule] for d in report.diagnostics]
    assert indices == sorted(indices)
    assert [d.rule for d in report.diagnostics] == ["R1", "G4", "R13b", "R35"]


# ─── DESIGN.md SECTION 8's WORKED EXAMPLE ───────────────────────────────────────────────────
#
# It is schema-valid - test/schema.spec.ts asserts that - and it fails exactly three semantic
# rules, all three consequences of the example predating F0.4:
#
#   * I1  x7 - its `blk_` ids are hand-written mnemonics, not digests.
#   * R29 x4 - its `content_hash` values are `blake2s:` with a 16-hex body; F0.4 pinned the digest
#              to `sha256:` + 64 hex, closing the gap Amendment 1 flagged.
#   * R36 x1 - `status` is "complete" while the inline_equation's `payload.image` is null.
#
# Asserted rather than skipped so that neither the example nor the rules can drift silently. F0.7's
# golden fixtures must pass all three; this document is documentation, not a fixture.


def test_worked_example_fails_exactly_i1_r29_and_r36() -> None:
    report = validate_paper(schema_valid(copy.deepcopy(WORKED_EXAMPLE)))
    counts: dict[str, int] = {}
    for diagnostic in report.diagnostics:
        counts[diagnostic.rule] = counts.get(diagnostic.rule, 0) + 1
    assert counts == {"R29": 4, "R36": 1, "I1": 7}
    assert report.warnings == ()


def test_worked_example_passes_every_other_tier_a_rule() -> None:
    report = validate_paper(
        schema_valid(copy.deepcopy(WORKED_EXAMPLE)),
        ValidateOptions(disabled_rules=frozenset({"I1", "R29", "R36"})),
    )
    assert format_diagnostics(report.diagnostics) == ""


def test_worked_example_r29_failures_are_the_hash_change_not_a_normalisation_disagreement() -> None:
    report = validate_paper(
        schema_valid(copy.deepcopy(WORKED_EXAMPLE)),
        ValidateOptions(disabled_rules=frozenset({"I1", "R36"})),
    )
    for diagnostic in report.diagnostics:
        assert diagnostic.rule == "R29"
        assert "blake2s:" in diagnostic.message
    # R28 is silent, so every text_normalised in the example IS the library's normalisation.
    assert not any(d.rule == "R28" for d in report.diagnostics)


# ─── RULES UNREACHABLE THROUGH THE JSON SCHEMA ──────────────────────────────────────────────
#
# G5 and R30 restate constraints the schema already enforces (allow_inf_nan false / bounded
# coordinates, and the Repair if/then). They cannot fire on a schema-valid document, which is why
# they have no conformance case - so they are asserted here by building the object behind the
# schema's back, which is exactly the situation they exist for: a caller that skipped it.


def test_g5_rejects_a_non_finite_polygon_vertex() -> None:
    def mutate(paper: Paper) -> None:
        paper.blocks[0].polygon[1][0] = float("inf")

    paper = bypass(mutate)
    report = validate_paper(paper, ValidateOptions(disabled_rules=frozenset({"R1"})))
    assert triples(report.diagnostics) == [
        {"rule": "G5", "severity": "error", "path": "blocks[0].polygon[1]"}
    ]


def test_g5_nan_bbox_silences_the_rules_that_would_compare_with_it() -> None:
    def mutate(paper: Paper) -> None:
        paper.blocks[0].bbox[2] = float("nan")

    paper = bypass(mutate)
    report = validate_paper(paper)
    assert triples(report.diagnostics) == [
        {"rule": "G5", "severity": "error", "path": "blocks[0].bbox"}
    ]


def test_r30_fires_on_an_unattributed_applied_model_repair() -> None:
    def mutate(paper: Paper) -> None:
        paper.blocks[4].repairs = [
            Repair.model_construct(
                kind="ocr_correction", applied=True, at=0, from_="Figure", to="Figure"
            )
        ]

    paper = bypass(mutate)
    report = validate_paper(paper)
    assert triples(report.diagnostics) == [
        {"rule": "R30", "severity": "error", "path": "blocks[4].repairs[0]"},
        {"rule": "R30", "severity": "error", "path": "blocks[4].repairs[0]"},
        {"rule": "R30", "severity": "error", "path": "blocks[4].repairs[0]"},
    ]
    assert "never overwrites source" in " ".join(d.message for d in report.diagnostics)


def test_r30b_model_naming_half_fires_on_a_deterministic_repair_that_names_a_model() -> None:
    def mutate(paper: Paper) -> None:
        paper.blocks[4].repairs = [
            Repair.model_construct(
                kind="whitespace",
                applied=True,
                from_="a  b",
                to="a b",
                model_id="openai/gpt-4o",
                prompt_hash="sha256:0000000000000000",
            )
        ]

    paper = bypass(mutate)
    report = validate_paper(paper)
    assert triples(report.diagnostics) == [
        {"rule": "R30b", "severity": "error", "path": "blocks[4].repairs[0]"}
    ]


# ─── THE API AROUND THE RULES ───────────────────────────────────────────────────────────────


def test_assert_valid_paper_is_silent_on_a_clean_document() -> None:
    assert_valid_paper(clean_paper())


def test_assert_valid_paper_raises_carrying_every_diagnostic() -> None:
    with pytest.raises(SemanticValidationError) as caught:
        assert_valid_paper(mutated({"set": "blocks/0/bbox/2", "value": 559}))
    assert len(caught.value.diagnostics) == 1
    assert "R1" in str(caught.value)


def test_a_warning_alone_never_fails_a_document() -> None:
    paper = mutated(
        {
            "set": "blocks/4/polygon",
            "value": [[320, 308], [558, 320], [400, 308], [558, 332], [320, 332]],
        }
    )
    report = validate_paper(paper)
    assert len(report.warnings) == 1
    assert report.errors == ()
    assert report.ok is True
    assert_valid_paper(paper)


def test_disabled_rules_silences_exactly_the_named_rule() -> None:
    paper = mutated(
        {"set": "blocks/0/bbox/2", "value": 559},
        {"set": "pages/0/width", "value": 600},
    )
    assert [d.rule for d in validate_paper(paper).diagnostics] == ["R1", "G4"]
    silenced = validate_paper(paper, ValidateOptions(disabled_rules=frozenset({"R1"})))
    assert [d.rule for d in silenced.diagnostics] == ["G4"]


def test_bbox_epsilon_is_a_tolerance_not_a_switch() -> None:
    paper = mutated({"set": "blocks/0/bbox/2", "value": 558.0000001})
    assert [d.rule for d in validate_paper(paper).diagnostics] == ["R1"]
    assert validate_paper(paper, ValidateOptions(bbox_epsilon_pt=1e-6)).diagnostics == ()


def test_semantic_rules_is_a_complete_unique_tier_a_index() -> None:
    ids = [rule.id for rule in SEMANTIC_RULES]
    assert len(set(ids)) == len(ids)
    assert all(rule.tier == "A" for rule in SEMANTIC_RULES)
    # R3 (out-of-crop-box jitter) and G8 (low page coverage) are the two heuristics: both mean
    # "suspicious", not "wrong", so both warn. See DESIGN.md 5.2 G8.
    assert [r.id for r in SEMANTIC_RULES if r.severity == "warning"] == ["R3", "G8"]
    # Tier B is deliberately absent: 32b belongs to Epic 1, 34 to Epic 3 (DESIGN.md 5.2).
    assert "R32b" not in ids
    assert "R34" not in ids


def test_format_diagnostics_renders_rule_severity_path_and_message() -> None:
    text = format_diagnostics(
        validate_paper(mutated({"set": "pages/0/width", "value": 600})).diagnostics
    )
    assert text.startswith("G4 error pages[0].width: ")


# ─── THE RULES WHOSE IMPLEMENTATION IS NOT A ONE-LINER ──────────────────────────────────────

_G8_NOISE = frozenset(
    {
        "R8",
        "R10",
        "R11",
        "R14",
        "R15",
        "R16",
        "R17",
        "R19",
        "R4",
        "R5",
        "R6",
        "R6b",
        "R7",
        "R13",
        "R21",
        "R28",
        "R29",
        "R35",
        "R37",
        "R38",
        "I1",
    }
)


def _two_hundred_stacked_boxes(side: float) -> Paper:
    """200 identical ``side`` x ``side`` boxes: they SUM to 200x the area they UNION to."""
    document = copy.deepcopy(CLEAN)
    page = document["pages"][0]
    page["width"] = 1000
    page["height"] = 1000
    page["crop_box"] = [0, 0, 1000, 1000]
    page["media_box"] = [0, 0, 1000, 1000]
    template = document["blocks"][0]
    clones = []
    for i in range(200):
        clone = copy.deepcopy(template)
        clone["order"] = i
        clone["doc_order"] = i
        clone["polygon"] = [[0, 0], [side, 0], [side, side], [0, side]]
        clone["bbox"] = [0, 0, side, side]
        clones.append(clone)
    document["blocks"] = clones
    document["pages"] = [page]
    return Paper.model_validate(document)


def test_g8_measures_the_union_not_the_sum() -> None:
    # On a 1000x1000 page the 1% floor is 10 000 pt2. 200 stacked 100x100 boxes sum to
    # 2 000 000 pt2 and union to exactly 10 000, so a summing implementation would pass both
    # halves of this test and a union one sits on the boundary - which is why both are asserted.
    options = ValidateOptions(disabled_rules=frozenset(_G8_NOISE))
    assert "G8" not in {
        d.rule for d in validate_paper(_two_hundred_stacked_boxes(100), options).diagnostics
    }
    assert "G8" in {
        d.rule for d in validate_paper(_two_hundred_stacked_boxes(99), options).diagnostics
    }


def test_r25_counts_code_points_not_utf16_units() -> None:
    # "\U0001d509(x)" is 4 code points and 5 UTF-16 units. A `.length`-based bound in the TS twin
    # would accept end=5; this asserts the two agree on 4.
    options = ValidateOptions(disabled_rules=frozenset({"I1", "R28", "R29"}))
    document = copy.deepcopy(CLEAN)
    block = document["blocks"][4]
    block["text"] = "\U0001d509(x)"
    block["text_normalised"] = "\U0001d509(x)"
    block["spans"] = [{"start": 0, "end": 4, "bbox": block["bbox"]}]
    ok = validate_paper(schema_valid(copy.deepcopy(document)), options)
    assert [d for d in ok.diagnostics if d.rule == "R25"] == []
    block["spans"] = [{"start": 0, "end": 5, "bbox": block["bbox"]}]
    bad = validate_paper(schema_valid(document), options)
    assert [d.rule for d in bad.diagnostics] == ["R25"]
    assert "= 4 code points" in bad.diagnostics[0].message


def _repair_rules(kind: str, from_: str, to: str) -> list[str]:
    paper = mutated(
        {
            "set": "blocks/4/repairs",
            "value": [{"kind": kind, "applied": True, "from": from_, "to": to}],
        }
    )
    return [d.rule for d in validate_paper(paper).diagnostics]


def test_r27_addresses_text_in_code_points_not_utf16_units() -> None:
    # "\U0001d509xyz" is 4 code points and 5 UTF-16 units. `at: 1` means "just after the glyph" in
    # both languages; a `.slice()` implementation in the TS twin would read "\ud834\udd09xy" and
    # reject a correct repair. Python's own slicing is already code points, so this test exists
    # here to pin the two languages to the SAME answer.
    document = copy.deepcopy(CLEAN)
    block = document["blocks"][4]
    block["text"] = "\U0001d509xyz"
    block["repairs"] = [
        {"kind": "whitespace", "applied": True, "at": 1, "from": "xyz", "to": "xyz"}
    ]
    report = validate_paper(
        schema_valid(document), ValidateOptions(disabled_rules=frozenset({"I1", "R28", "R29"}))
    )
    assert triples(report.diagnostics) == []


def test_r29_does_not_renormalise_text_normalised() -> None:
    """normalise_text is deliberately NOT idempotent (Amendment 1 § A: its output is not
    guaranteed to be NFC), so normalising ``text_normalised`` a SECOND time re-composes a ligature
    expansion sitting in front of a combining mark: normalise_text("\ufb01\u0302") is
    "f i \u0302" and normalising that gives "f \u00ee". A producer that derived content_hash with
    the library's own documented API - identity.content_hash(block.text) - was therefore failed by
    R29 on a LEGITIMATE document."""
    document = copy.deepcopy(CLEAN)
    block = document["blocks"][4]
    block["text"] = "\ufb01\u0302 tail"
    block["text_normalised"] = normalise_text(block["text"])
    block["content_hash"] = content_hash(block["text"])
    block["block_id"] = recompute_block_id(
        BlockIdInput(
            source_hash=document["source_hash"][len("sha256:") :],
            page_index=block["page_index"],
            x0=block["bbox"][0],
            y0=block["bbox"][1],
            block_type=block["type"],
            text=block["text"],
        )
    )
    # The subject really is non-idempotent, or this test proves nothing.
    assert normalise_text(block["text_normalised"]) != block["text_normalised"]
    report = validate_paper(schema_valid(document))
    assert [d for d in report.diagnostics if d.rule in {"R28", "R29"}] == []

    # ...and it still catches a genuinely wrong digest.
    block["content_hash"] = content_hash("something else entirely")
    after = validate_paper(schema_valid(document))
    assert len([d for d in after.diagnostics if d.rule == "R29"]) == 1


def test_r30b_dehyphenate_transform_is_exactly_hyphen_plus_break_and_soft_hyphen() -> None:
    assert _repair_rules("dehyphenate", "exam-\nple", "example") == []
    assert _repair_rules("dehyphenate", "exam-\r\n  ple", "example") == []
    assert _repair_rules("dehyphenate", "exam­ple", "example") == []
    assert _repair_rules("dehyphenate", "exam‐\nple", "example") == []
    # A hyphen with no line break is a REAL hyphen and must survive.
    assert _repair_rules("dehyphenate", "state-of-the-art", "stateoftheart") == ["R30b"]
    # Dehyphenation may not also change a letter.
    assert _repair_rules("dehyphenate", "exam-\nple", "sample") == ["R30b"]


def test_r30b_reorder_is_a_multiset_check() -> None:
    assert _repair_rules("reorder", "a b c", "c b a") == []
    assert _repair_rules("reorder", "a b b", "b a b") == []
    # Same letters, different multiset: a duplicate is not a permutation of a singleton.
    assert _repair_rules("reorder", "a b b", "a a b") == ["R30b"]
    # Whitespace is the CONTRACT's 26 code points, not the runtime's \\s. U+00A0 is in the set and
    # U+200B (zero width space, which Python's str.split() also ignores... it does not) is not.
    assert _repair_rules("reorder", "a b", "b a") == []


def test_nfkc_is_a_runtime_call_and_this_runtime_is_pinned() -> None:
    """The one place this module depends on the runtime's Unicode tables rather than a pinned one.

    Therefore the one place the TS and Python twins can legitimately disagree. The count is
    asserted per Unicode version so a Python upgrade fails here instead of silently moving what "a
    deterministic unicode_normalise repair" means.

    Measured 2026-07-30: Python 3.12 (UCD 15.0.0) decomposes 4928 code points under NFKC; Node 22
    (Unicode 17.0) decomposes 4965. The 37-code-point difference is U+A7F1 plus U+1CCD6..U+1CCF9,
    all added after 15.0.0.
    """
    expected = {"15.0.0": 4928, "15.1.0": 4928, "17.0.0": 4965}
    version = unicodedata.unidata_version
    decomposing = sum(
        1
        for cp in range(0x110000)
        if not (0xD800 <= cp <= 0xDFFF) and unicodedata.normalize("NFKC", chr(cp)) != chr(cp)
    )
    print(
        f"[test_validate] Python carries UCD {version}; NFKC decomposes {decomposing} code points. "
        f"Node 22 (Unicode 17.0) decomposes 4965 - rule 30b's unicode_normalise check forks on the "
        f"difference."
    )
    assert version in expected, (
        f"unrecorded Unicode version {version}: re-measure the NFKC divergence against the "
        f"TypeScript twin before trusting rule 30b's unicode_normalise class"
    )
    assert decomposing == expected[version]
    # The concrete fork, named so it cannot be waved away as theoretical.
    assert (unicodedata.normalize("NFKC", "\U0001ccd6") == "\U0001ccd6") == (version == "15.0.0")


def test_r20_reports_a_cycle_once_not_once_per_entry_point() -> None:
    document = copy.deepcopy(CLEAN)
    a, b = document["blocks"][8], document["blocks"][9]
    a["parent_id"], b["parent_id"] = b["block_id"], a["block_id"]
    # A third block whose chain leads INTO the cycle from outside. The diagnostic must key on the
    # cycle, not on the trail that reached it, or every ancestor reports the same defect again.
    document["blocks"][2]["parent_id"] = a["block_id"]
    report = validate_paper(
        schema_valid(document),
        ValidateOptions(disabled_rules=frozenset({"R17", "R18", "R19", "R14", "R38"})),
    )
    assert [d.rule for d in report.diagnostics] == ["R20"]
    assert "the parent graph is cyclic" in report.diagnostics[0].message


def test_i1_recomputes_from_the_blocks_own_anchor() -> None:
    def shift(delta: float) -> list[str]:
        document = copy.deepcopy(CLEAN)
        block = document["blocks"][4]
        block["polygon"] = [[x + delta, y] for x, y in block["polygon"]]
        block["bbox"] = [
            block["bbox"][0] + delta,
            block["bbox"][1],
            block["bbox"][2] + delta,
            block["bbox"][3],
        ]
        return [d.rule for d in validate_paper(schema_valid(document)).diagnostics]

    # 0.4 pt is inside the 1.0 pt quantisation bucket: the id must NOT change.
    assert shift(0.4) == []
    assert shift(4) == ["I1"]
