/**
 * document-ir/validate.spec — the F0.4 semantic-validator acceptance test.
 *
 * WHAT IS BEING GRADED AGAINST WHAT.
 *
 *   · `conformance/validator-clean.json` is a semantically perfect PaperIR document, GENERATED by
 *     `conformance/generate-validator-clean.py` so that `block_id`, `text_normalised` and
 *     `content_hash` are real rather than invented.
 *   · `conformance/validator-cases.json` is HAND-WRITTEN: 68 patches of that document, each with
 *     the exact ordered list of `(rule, severity, path)` triples the validator must produce.
 *     `python/tests/test_validate.py` asserts the same file. Neither language is the other's
 *     oracle; both are graded against one hand-written recording.
 *   · `test/cases/001-worked-example.json` — DESIGN.md §8's documented worked example — is
 *     validated too, and it FAILS three rules. That is a finding about the document, not about
 *     the validator, and it is asserted exactly so it cannot be quietly "fixed" either way.
 *
 * MESSAGES ARE NOT PART OF THE CROSS-LANGUAGE CONTRACT (they interpolate numbers, and
 * `String(1.0)` is `"1"` in JS while `str(1.0)` is `"1.0"` in Python). The triples are.
 *
 * Every mutated document is re-parsed through `PaperSchema` first, which is what makes the
 * cases file's central claim checkable: these are all defects the JSON Schema CANNOT see.
 */
// oxlint-disable typescript/no-explicit-any -- the conformance files are deliberately untyped JSON.
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { Block, Paper } from '../src/generated/types.js';
import { blockId, contentHash, normaliseText } from '../src/identity.js';
import { PaperSchema } from '../src/generated/zod.js';
import {
  SEMANTIC_RULES,
  SemanticValidationError,
  assertValidPaper,
  formatDiagnostics,
  validatePaper,
  type Diagnostic,
  type ValidateOptions,
} from '../src/validate.js';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');

const CLEAN = JSON.parse(readFileSync(join(PKG, 'conformance/validator-clean.json'), 'utf8'))
  .document as Record<string, any>;
const CASES = JSON.parse(
  readFileSync(join(PKG, 'conformance/validator-cases.json'), 'utf8'),
) as Record<string, any>;
const WORKED_EXAMPLE = JSON.parse(
  readFileSync(join(PKG, 'test/cases/001-worked-example.json'), 'utf8'),
).document as Record<string, any>;

// ─── THE PATCHER (see validator-cases.json "patch_ops") ─────────────────────────────────────

function readPath(root: unknown, path: string): unknown {
  let node: any = root;
  if (path === '') return node;
  for (const segment of path.split('/')) {
    node = Array.isArray(node) ? node[Number(segment)] : node[segment];
  }
  return node;
}

/** A string value beginning with `@` is a path read out of the UNMUTATED clean document. */
function resolveValue(value: unknown): unknown {
  if (typeof value === 'string') {
    return value.startsWith('@') ? structuredClone(readPath(CLEAN, value.slice(1))) : value;
  }
  if (Array.isArray(value)) return value.map(resolveValue);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, resolveValue(v)]),
    );
  }
  return value;
}

function applyOps(document: Record<string, any>, ops: readonly Record<string, any>[]): void {
  for (const op of ops) {
    if ('set' in op || 'delete' in op) {
      const path = (op['set'] ?? op['delete']).split('/') as string[];
      const parent: any = readPath(document, path.slice(0, -1).join('/'));
      const last = path[path.length - 1] as string;
      if ('delete' in op) {
        if (Array.isArray(parent)) parent.splice(Number(last), 1);
        else delete parent[last];
      } else if (Array.isArray(parent)) {
        parent[Number(last)] = resolveValue(op['value']);
      } else {
        parent[last] = resolveValue(op['value']);
      }
    } else if ('append' in op) {
      (readPath(document, op['append']) as unknown[]).push(resolveValue(op['value']));
    } else {
      throw new Error(`unknown patch op ${JSON.stringify(op)}`);
    }
  }
}

function optionsFor(raw: Record<string, any> | undefined): ValidateOptions {
  if (raw === undefined) return {};
  const out: { -readonly [K in keyof ValidateOptions]: ValidateOptions[K] } = {};
  if (raw['disabled_rules'] !== undefined) out.disabledRules = raw['disabled_rules'] as string[];
  if (raw['out_of_crop_box_error_fraction'] !== undefined) {
    out.outOfCropBoxErrorFraction = raw['out_of_crop_box_error_fraction'] as number;
  }
  if (raw['min_page_coverage_fraction'] !== undefined) {
    out.minPageCoverageFraction = raw['min_page_coverage_fraction'] as number;
  }
  return out;
}

const triples = (diagnostics: readonly Diagnostic[]): Array<Record<string, string>> =>
  diagnostics.map((d) => ({ rule: d.rule, severity: d.severity, path: d.path }));

/** Every mutated document must still satisfy the JSON Schema — that is the file's whole claim. */
function schemaValid(document: Record<string, any>): Paper {
  return PaperSchema.parse(document) as unknown as Paper;
}

// ─── THE CONFORMANCE CASES ──────────────────────────────────────────────────────────────────

describe('conformance/validator-cases.json', () => {
  const cases = CASES['cases'] as Array<Record<string, any>>;

  it('covers every rule this module claims to implement', () => {
    const exercised = new Set<string>();
    for (const testCase of cases) {
      for (const expected of testCase['expect'] as Array<Record<string, string>>) {
        exercised.add(expected['rule'] as string);
      }
    }
    // The three rules a schema-valid document CANNOT reach are asserted separately, behind the
    // schema's back — see the "unreachable through the JSON Schema" block below.
    for (const rule of ['G5', 'R30']) exercised.add(rule);
    const missing = SEMANTIC_RULES.map((r) => r.id).filter((id) => !exercised.has(id));
    expect(missing, `rules with no test: ${missing.join(', ')}`).toEqual([]);
  });

  for (const testCase of cases) {
    const name = testCase['name'] as string;
    it(name, () => {
      const document = structuredClone(CLEAN);
      applyOps(document, testCase['ops'] as Array<Record<string, any>>);
      const paper = schemaValid(document);
      const report = validatePaper(paper, optionsFor(testCase['options'] as never));
      expect(triples(report.diagnostics), formatDiagnostics(report.diagnostics)).toEqual(
        testCase['expect'],
      );
      expect(report.ok).toBe(report.errors.length === 0);
      expect(report.errors.length + report.warnings.length).toBe(report.diagnostics.length);
    });
  }
});

describe('the clean document', () => {
  it('is schema-valid and semantically silent', () => {
    const report = validatePaper(schemaValid(structuredClone(CLEAN)));
    expect(formatDiagnostics(report.diagnostics)).toBe('');
    expect(report.ok).toBe(true);
  });

  it('validates identically on repeated runs — no iteration-order dependence', () => {
    const paper = schemaValid(structuredClone(CLEAN));
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [
      { set: 'blocks/0/bbox/2', value: 559 },
      { set: 'blocks/1/order', value: 2 },
      { set: 'confidence/overall', value: null },
    ]);
    const broken = schemaValid(mutated);
    for (let round = 0; round < 8; round += 1) {
      expect(validatePaper(paper).diagnostics).toEqual([]);
      expect(triples(validatePaper(broken).diagnostics)).toEqual(
        triples(validatePaper(broken).diagnostics),
      );
    }
    expect(validatePaper(broken).diagnostics.length).toBe(4);
  });

  it('emits diagnostics in SEMANTIC_RULES order', () => {
    const order = new Map(SEMANTIC_RULES.map((r, i) => [r.id, i]));
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [
      { set: 'blocks/0/bbox/2', value: 559 },
      { set: 'confidence/overall', value: null },
      { set: 'references/0/venue', value: 'NeurIPS' },
      { set: 'pages/0/width', value: 600 },
    ]);
    const report = validatePaper(schemaValid(mutated));
    const indices = report.diagnostics.map((d) => order.get(d.rule) as number);
    expect(indices).toEqual([...indices].toSorted((a, b) => a - b));
    expect(report.diagnostics.map((d) => d.rule)).toEqual(['R1', 'G4', 'R13b', 'R35']);
  });
});

// ─── DESIGN.md §8's WORKED EXAMPLE ──────────────────────────────────────────────────────────

describe("DESIGN.md §8's worked example", () => {
  /**
   * It is schema-valid — `test/schema.spec.ts` asserts that — and it fails exactly three semantic
   * rules, all three of which are consequences of the example predating F0.4:
   *
   *   · I1  ×7 — its `blk_` ids are hand-written mnemonics, not digests.
   *   · R29 ×4 — its four `content_hash` values are `blake2s:` with a 16-hex body; F0.4 pinned the
   *              digest to `sha256:` + 64 hex (identity.ts `contentHash`, closing the gap
   *              Amendment 1 § "What Wave 1 must know" flagged).
   *   · R36 ×1 — `status` is `"complete"` while the inline_equation's `payload.image` is `null`.
   *
   * Asserted rather than skipped so that neither the example nor the rules can drift silently.
   * F0.7's golden fixtures must pass all three; this document is documentation, not a fixture.
   */
  const paper = schemaValid(WORKED_EXAMPLE);

  it('fails exactly I1 x7, R29 x4 and R36 x1 — and nothing else', () => {
    const report = validatePaper(paper);
    const counts = new Map<string, number>();
    for (const d of report.diagnostics) counts.set(d.rule, (counts.get(d.rule) ?? 0) + 1);
    expect(Object.fromEntries(counts)).toEqual({ R29: 4, R36: 1, I1: 7 });
    expect(report.warnings).toEqual([]);
  });

  it('passes every other Tier A rule once those three are disabled', () => {
    const report = validatePaper(paper, { disabledRules: ['I1', 'R29', 'R36'] });
    expect(formatDiagnostics(report.diagnostics)).toBe('');
  });

  it('the R29 failures are the blake2s/sha256 change, not a normalisation disagreement', () => {
    const report = validatePaper(paper, { disabledRules: ['I1', 'R36'] });
    for (const d of report.diagnostics) {
      expect(d.rule).toBe('R29');
      expect(d.message).toContain('blake2s:');
    }
    // R28 is silent, so every text_normalised in the example IS the library's normalisation.
    expect(report.diagnostics.some((d) => d.rule === 'R28')).toBe(false);
  });
});

// ─── RULES UNREACHABLE THROUGH THE JSON SCHEMA ──────────────────────────────────────────────

describe('rules unreachable through the JSON Schema', () => {
  /**
   * G5 and R30 restate constraints the schema already enforces (`allow_inf_nan: false` / bounded
   * coordinates, and the `Repair` if/then). They cannot fire on a schema-valid document, which is
   * why they have no conformance case — so they are asserted here by building the object behind
   * the schema's back, which is exactly the situation they exist for: a caller that skipped it.
   */
  const bypass = (mutate: (paper: any) => void): Paper => {
    const paper: any = structuredClone(CLEAN);
    mutate(paper);
    return paper as Paper;
  };

  it('G5 fires on a non-finite polygon vertex', () => {
    const paper = bypass((p) => {
      p.blocks[0].polygon[1][0] = Number.POSITIVE_INFINITY;
    });
    const report = validatePaper(paper, { disabledRules: ['R1'] });
    expect(triples(report.diagnostics)).toEqual([
      { rule: 'G5', severity: 'error', path: 'blocks[0].polygon[1]' },
    ]);
  });

  it('G5 fires on a NaN bbox, and rules 1/2/3/G8 then stay silent rather than compare with NaN', () => {
    const paper = bypass((p) => {
      p.blocks[0].bbox[2] = Number.NaN;
    });
    const report = validatePaper(paper);
    expect(triples(report.diagnostics)).toEqual([
      { rule: 'G5', severity: 'error', path: 'blocks[0].bbox' },
    ]);
  });

  it('R30 fires on a model-authored repair with no model_id, no prompt_hash and applied:true', () => {
    const paper = bypass((p) => {
      p.blocks[4].repairs = [
        { kind: 'ocr_correction', applied: true, at: 0, from: 'Figure', to: 'Figure' },
      ];
    });
    const report = validatePaper(paper);
    expect(triples(report.diagnostics)).toEqual([
      { rule: 'R30', severity: 'error', path: 'blocks[4].repairs[0]' },
      { rule: 'R30', severity: 'error', path: 'blocks[4].repairs[0]' },
      { rule: 'R30', severity: 'error', path: 'blocks[4].repairs[0]' },
    ]);
    expect(report.diagnostics.map((d) => d.message).join(' ')).toContain('never overwrites source');
  });

  it("R30b's model-naming half fires on a deterministic repair that names a model", () => {
    const paper = bypass((p) => {
      p.blocks[4].repairs = [
        {
          kind: 'whitespace',
          applied: true,
          from: 'a  b',
          to: 'a b',
          model_id: 'openai/gpt-4o',
          prompt_hash: 'sha256:0000000000000000',
        },
      ];
    });
    const report = validatePaper(paper);
    expect(triples(report.diagnostics)).toEqual([
      { rule: 'R30b', severity: 'error', path: 'blocks[4].repairs[0]' },
    ]);
  });
});

// ─── THE API AROUND THE RULES ───────────────────────────────────────────────────────────────

describe("the validator's API", () => {
  it('assertValidPaper is silent on a clean document', () => {
    expect(() => {
      assertValidPaper(schemaValid(structuredClone(CLEAN)));
    }).not.toThrow();
  });

  it('assertValidPaper throws SemanticValidationError carrying every diagnostic', () => {
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [{ set: 'blocks/0/bbox/2', value: 559 }]);
    try {
      assertValidPaper(schemaValid(mutated));
      expect.unreachable('expected SemanticValidationError');
    } catch (error) {
      expect(error).toBeInstanceOf(SemanticValidationError);
      const diagnostics = (error as SemanticValidationError).diagnostics;
      expect(diagnostics).toHaveLength(1);
      expect((error as Error).message).toContain('R1');
    }
  });

  it('a WARNING alone never fails a document', () => {
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [
      {
        set: 'blocks/4/polygon',
        value: [
          [320, 308],
          [558, 320],
          [400, 308],
          [558, 332],
          [320, 332],
        ],
      },
    ]);
    const paper = schemaValid(mutated);
    const report = validatePaper(paper);
    expect(report.warnings).toHaveLength(1);
    expect(report.errors).toEqual([]);
    expect(report.ok).toBe(true);
    expect(() => {
      assertValidPaper(paper);
    }).not.toThrow();
  });

  it('disabledRules silences exactly the named rule and nothing else', () => {
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [
      { set: 'blocks/0/bbox/2', value: 559 },
      { set: 'pages/0/width', value: 600 },
    ]);
    const paper = schemaValid(mutated);
    expect(validatePaper(paper).diagnostics.map((d) => d.rule)).toEqual(['R1', 'G4']);
    expect(validatePaper(paper, { disabledRules: ['R1'] }).diagnostics.map((d) => d.rule)).toEqual([
      'G4',
    ]);
  });

  it('bboxEpsilonPt is a tolerance, not a switch', () => {
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [{ set: 'blocks/0/bbox/2', value: 558.0000001 }]);
    const paper = schemaValid(mutated);
    expect(validatePaper(paper).diagnostics.map((d) => d.rule)).toEqual(['R1']);
    expect(validatePaper(paper, { bboxEpsilonPt: 1e-6 }).diagnostics).toEqual([]);
  });

  it('SEMANTIC_RULES is a complete, unique, Tier-A index of the implemented rules', () => {
    const ids = SEMANTIC_RULES.map((r) => r.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(SEMANTIC_RULES.every((r) => r.tier === 'A')).toBe(true);
    // R3 (out-of-crop-box jitter) and G8 (low page coverage) are the two heuristics: both mean
    // "suspicious", not "wrong", so both warn. See DESIGN.md §5.2 G8.
    expect(SEMANTIC_RULES.filter((r) => r.severity === 'warning').map((r) => r.id)).toEqual([
      'R3',
      'G8',
    ]);
    // Tier B is deliberately absent: 32b belongs to Epic 1, 34 to Epic 3 (DESIGN.md §5.2).
    expect(ids).not.toContain('R32b');
    expect(ids).not.toContain('R34');
  });

  it('formatDiagnostics renders rule, severity, path and message', () => {
    const mutated = structuredClone(CLEAN);
    applyOps(mutated, [{ set: 'pages/0/width', value: 600 }]);
    const text = formatDiagnostics(validatePaper(schemaValid(mutated)).diagnostics);
    expect(text.startsWith('G4 error pages[0].width: ')).toBe(true);
  });
});

// ─── THE RULES THAT NEEDED THEIR OWN ARITHMETIC ─────────────────────────────────────────────

describe('the rules whose implementation is not a one-liner', () => {
  it('G8 measures the UNION of the bboxes, not their sum', () => {
    // 200 identical 100x100 boxes sum to 2 000 000 pt² and union to 10 000 pt². On a 1000x1000
    // page the 1 % floor is 10 000 pt², so a summing implementation passes this and a union one
    // sits exactly on the boundary — which is why it is asserted from both sides.
    const build = (side: number): Paper => {
      const document: any = structuredClone(CLEAN);
      const page = document.pages[0];
      page.width = 1000;
      page.height = 1000;
      page.crop_box = [0, 0, 1000, 1000];
      page.media_box = [0, 0, 1000, 1000];
      const template = document.blocks[0];
      const clones = Array.from({ length: 200 }, (_, i) => ({
        ...structuredClone(template),
        block_id: template.block_id,
        order: i,
        doc_order: i,
        polygon: [
          [0, 0],
          [side, 0],
          [side, side],
          [0, side],
        ],
        bbox: [0, 0, side, side],
      }));
      document.blocks = clones;
      document.pages = [page];
      return document as Paper;
    };
    const disabled = {
      disabledRules: [
        'R8',
        'R10',
        'R11',
        'R14',
        'R15',
        'R17',
        'R19',
        'R4',
        'R5',
        'R6',
        'R6b',
        'R7',
        'R13',
        'R21',
        'R38',
        'R37',
        'R28',
        'R29',
        'I1',
        'R35',
        'R16',
      ],
    };
    expect(validatePaper(build(100), disabled).diagnostics.map((d) => d.rule)).not.toContain('G8');
    expect(validatePaper(build(99), disabled).diagnostics.map((d) => d.rule)).toContain('G8');
  });

  it('R25/R27 count CODE POINTS, not UTF-16 code units', () => {
    // "𝔉(x)" is 4 code points and 5 UTF-16 units. A `.length`-based bound would accept end=5.
    const document: any = structuredClone(CLEAN);
    const block = document.blocks[4];
    block.text = '\u{1D509}(x)';
    block.text_normalised = '\u{1D509}(x)';
    block.spans = [{ start: 0, end: 4, bbox: block.bbox }];
    const ok = validatePaper(document as Paper, {
      disabledRules: ['I1', 'R29', 'R28'],
    });
    expect(ok.diagnostics.filter((d) => d.rule === 'R25')).toEqual([]);
    block.spans = [{ start: 0, end: 5, bbox: block.bbox }];
    const bad = validatePaper(document as Paper, { disabledRules: ['I1', 'R29', 'R28'] });
    expect(bad.diagnostics.map((d) => d.rule)).toEqual(['R25']);
    expect(bad.diagnostics[0]?.message).toContain('= 4 code points');
  });

  it('R27 addresses text in CODE POINTS, so an astral character does not shift every offset', () => {
    // "𝔉xyz" is 4 code points and 5 UTF-16 units. `at: 1` means "just after the 𝔉" in both
    // languages; a `.slice()` implementation would read "\uDD09xy" and reject a correct repair.
    const document: any = structuredClone(CLEAN);
    const block = document.blocks[4];
    block.text = '\u{1D509}xyz';
    block.repairs = [{ kind: 'whitespace', applied: true, at: 1, from: 'xyz', to: 'xyz' }];
    const report = validatePaper(document as Paper, {
      disabledRules: ['I1', 'R28', 'R29'],
    });
    expect(triples(report.diagnostics)).toEqual([]);
  });

  it("R30b's dehyphenate transform removes a lone soft hyphen and a hyphen+break, nothing else", () => {
    const repair = (from: string, to: string): Diagnostic[] => {
      const document: any = structuredClone(CLEAN);
      document.blocks[4].repairs = [{ kind: 'dehyphenate', applied: true, from, to }];
      return [...validatePaper(document as Paper).diagnostics];
    };
    expect(repair('exam-\nple', 'example')).toEqual([]);
    expect(repair('exam-\r\n  ple', 'example')).toEqual([]);
    expect(repair('exam­ple', 'example')).toEqual([]);
    expect(repair('exam‐\nple', 'example')).toEqual([]);
    // A hyphen with no line break is a REAL hyphen and must survive.
    expect(repair('state-of-the-art', 'stateoftheart').map((d) => d.rule)).toEqual(['R30b']);
    // Dehyphenation may not also change a letter.
    expect(repair('exam-\nple', 'sample').map((d) => d.rule)).toEqual(['R30b']);
  });

  it("R30b's reorder check is a multiset, so it is blind to token ORDER and nothing else", () => {
    const repair = (from: string, to: string): string[] => {
      const document: any = structuredClone(CLEAN);
      document.blocks[4].repairs = [{ kind: 'reorder', applied: true, from, to }];
      return validatePaper(document as Paper).diagnostics.map((d) => d.rule);
    };
    expect(repair('a b c', 'c b a')).toEqual([]);
    expect(repair('a b b', 'b a b')).toEqual([]);
    // Same letters, different multiset: a duplicate is not a permutation of a singleton.
    expect(repair('a b b', 'a a b')).toEqual(['R30b']);
    // Whitespace is the CONTRACT's 26 code points, not the runtime's \s.
    expect(repair('a b', 'b a')).toEqual([]);
  });

  it("R30b's unicode_normalise is a RUNTIME call, and this runtime's NFKC is pinned", () => {
    /**
     * The one place this module depends on the runtime's Unicode tables rather than on a pinned
     * one, and therefore the one place the TS and Python twins can legitimately disagree. The
     * count is asserted per Unicode version so that a Node upgrade fails here instead of silently
     * moving what "a deterministic unicode_normalise repair" means.
     *
     * Measured 2026-07-30: Node 22 (Unicode 17.0) decomposes 4965 code points under NFKC; Python
     * 3.12 (UCD 15.0.0) decomposes 4928. The 37-code-point difference is U+A7F1 plus
     * U+1CCD6…U+1CCF9, all added after 15.0.0.
     */
    const expected: Record<string, number> = { '15.0.0': 4928, '15.1': 4928, '17.0': 4965 };
    const version = process.versions.unicode ?? 'unknown';
    let decomposing = 0;
    for (let cp = 0; cp < 0x110000; cp += 1) {
      if (cp >= 0xd800 && cp <= 0xdfff) continue;
      const ch = String.fromCodePoint(cp);
      if (ch.normalize('NFKC') !== ch) decomposing += 1;
    }
    console.log(
      `[validate.spec] Node ${process.version} carries Unicode ${version}; NFKC decomposes ` +
        `${String(decomposing)} code points. Python 3.12 (UCD 15.0.0) decomposes 4928 — rule 30b's ` +
        `unicode_normalise check forks on the difference.`,
    );
    expect(
      expected[version],
      `unrecorded Unicode version ${version}: re-measure the NFKC divergence against the Python ` +
        `twin before trusting rule 30b's unicode_normalise class`,
    ).toBe(decomposing);
    // The concrete fork, named so it cannot be waved away as theoretical.
    expect('\u{1CCD6}'.normalize('NFKC') === '\u{1CCD6}').toBe(version === '15.0.0');
  });

  it('R29 does not re-normalise text_normalised — normaliseText is NOT idempotent', () => {
    // `normalise()` output is deliberately not NFC (Amendment 1 § A), so normalising
    // `text_normalised` a SECOND time re-composes a ligature expansion sitting in front of a
    // combining mark: normaliseText("\uFB01\u0302") is "f i \u0302" and normalising that gives
    // "f \u00EE". A producer that derived content_hash with the library's own documented API —
    // `identity.contentHash(block.text)` — was therefore failed by R29 on a LEGITIMATE document.
    const document: any = structuredClone(CLEAN);
    const block = document.blocks[4];
    block.text = '\ufb01\u0302 tail';
    block.text_normalised = normaliseText(block.text);
    block.content_hash = contentHash(block.text);
    block.block_id = blockId({
      source_hash: document.source_hash.slice('sha256:'.length),
      page_index: block.page_index,
      x0: block.bbox[0],
      y0: block.bbox[1],
      block_type: block.type,
      text: block.text,
    });
    // The subject really is non-idempotent, or this test proves nothing.
    expect(normaliseText(block.text_normalised)).not.toBe(block.text_normalised);
    const report = validatePaper(document as Paper);
    expect(report.diagnostics.filter((d) => d.rule === 'R29' || d.rule === 'R28')).toEqual([]);

    // …and it still catches a genuinely wrong digest.
    block.content_hash = contentHash('something else entirely');
    expect(
      validatePaper(document as Paper).diagnostics.filter((d) => d.rule === 'R29'),
    ).toHaveLength(1);
  });

  it('R20 finds a cycle without walking it forever, and reports it ONCE', () => {
    const document: any = structuredClone(CLEAN);
    const [a, b] = [document.blocks[8], document.blocks[9]];
    a.parent_id = b.block_id;
    b.parent_id = a.block_id;
    // A third block whose chain leads INTO the cycle from outside. The diagnostic must key on the
    // cycle, not on the trail that reached it, or every ancestor reports the same defect again.
    document.blocks[2].parent_id = a.block_id;
    const report = validatePaper(document as Paper, {
      disabledRules: ['R17', 'R18', 'R19', 'R14', 'R38'],
    });
    expect(report.diagnostics.map((d) => d.rule)).toEqual(['R20']);
    expect(report.diagnostics[0]?.message).toContain('the parent graph is cyclic');
  });

  it("I1 recomputes from the block's own anchor, so a moved block gets a new id", () => {
    // 0.4 pt is inside the 1.0 pt quantisation bucket: the id must NOT change.
    const shift = (delta: number): string[] => {
      const doc: any = structuredClone(CLEAN);
      const block = doc.blocks[4];
      block.polygon = block.polygon.map(([x, y]: [number, number]) => [x + delta, y]);
      block.bbox = [block.bbox[0] + delta, block.bbox[1], block.bbox[2] + delta, block.bbox[3]];
      return validatePaper(doc as Paper).diagnostics.map((d) => d.rule);
    };
    expect(shift(0.4)).toEqual([]);
    expect(shift(4)).toEqual(['I1']);
  });
});

// ─── SANITY: THE CASES FILE ITSELF ──────────────────────────────────────────────────────────

describe('the conformance files', () => {
  it('names 68 cases and every one of them mutates a schema-valid document', () => {
    const cases = CASES['cases'] as Array<Record<string, any>>;
    expect(cases).toHaveLength(68);
    expect(new Set(cases.map((c) => c['name'])).size).toBe(cases.length);
  });

  it('the clean document carries real, recomputed block ids', () => {
    const blocks = CLEAN['blocks'] as Block[];
    expect(blocks).toHaveLength(12);
    for (const block of blocks) expect(block.block_id).toMatch(/^blk_[a-z2-7]{16}$/);
    expect(new Set(blocks.map((b) => b.block_id)).size).toBe(blocks.length);
  });
});
