/**
 * anchoring/targets.spec — "Anchors resolve for: PDF text, Guided paragraph, equation, part of an
 * equation, figure, region inside a figure, table row, table cell, algorithm, citation."
 *
 * All ten resolve through the SAME mechanism, and that is the design rather than a coincidence: a
 * table cell is a `BlockSelector` with a `cellRef`, an equation is a `ShapeSelector` plus its LaTeX
 * as the quote, and part of an equation is a normalised sub-rect of its parent's bbox. Nothing here
 * needs a per-kind resolver, so nothing here can rot per kind.
 *
 * SINGLE POINTS OF FAILURE, stated because the fixture set has them: there is exactly ONE table in
 * the whole set (`neural-odes`, 1 table / 5 rows / 24 cells) and exactly ONE `algorithm` block. If
 * that fixture is wrong about tables, the set is wrong about tables and so is this test. Citation
 * data does not exist in the set at all and is generated by `make-citation-fixture.ts`.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { captureAnchor } from '../src/capture.js';
import { indexDocument, type IndexedBlock, type PaperSource } from '../src/document.js';
import { resolveAnchor } from '../src/resolve.js';
import { Tier, type SubTarget, type TargetKind } from '../src/types.js';
import { loadFixture } from './fixtures.js';

const CITATION_FIXTURE = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/citation-nav.paperir.json', import.meta.url)), 'utf8'),
) as PaperSource;

function firstOfType(doc: ReturnType<typeof indexDocument>, type: string): IndexedBlock {
  const block = doc.blocks.find((b) => b.type === type);
  if (block === undefined) throw new Error(`no ${type} block in this fixture`);
  return block;
}

function firstQuad(anchor: { selectors: readonly { type: string }[] }): number[] {
  const shape = anchor.selectors.find((s) => s.type === 'ShapeSelector') as
    | { quads: readonly number[][] }
    | undefined;
  const quad = shape?.quads[0];
  if (quad === undefined) throw new Error('anchor carries no ShapeSelector quad');
  return [...quad];
}

interface Case {
  readonly kind: TargetKind;
  readonly fixture: PaperSource;
  readonly blockType: string;
  readonly subTarget?: SubTarget;
  readonly range?: [number, number];
}

const attention = loadFixture('attention-is-all-you-need');
const neuralOdes = loadFixture('neural-odes-mathheavy');
const resnet = loadFixture('resnet-cvpr-2col');

const CASES: Case[] = [
  { kind: 'text', fixture: resnet, blockType: 'paragraph', range: [10, 90] },
  { kind: 'equation', fixture: attention, blockType: 'equation' },
  {
    kind: 'equation_part',
    fixture: attention,
    blockType: 'equation',
    // The left third of the formula's own box — "part of equation (1)". Expressed as a fraction of
    // the parent bbox so it re-projects onto a re-parsed block of a different size, which is what
    // makes it survive a re-parse WITHOUT any LaTeX existing. `neural-odes`' five display equations
    // carry no `latex` at all, so a LaTeX-offset-only design would fail on a third of the corpus.
    subTarget: { kind: 'equation_part', normalisedRect: [0, 0, 0.34, 1] },
  },
  { kind: 'figure', fixture: resnet, blockType: 'figure' },
  {
    kind: 'figure_region',
    fixture: resnet,
    blockType: 'figure',
    // Figure INTERIORS are not addressable in this IR — axis labels and legend text are at most
    // `payload.detected_labels`, never blocks. A normalised sub-rect is therefore the ONLY way to
    // point inside a figure, and it is the right one: it survives a re-parse as long as the figure
    // bbox is recovered.
    subTarget: { kind: 'figure_region', normalisedRect: [0.25, 0.1, 0.75, 0.6] },
  },
  { kind: 'table_row', fixture: neuralOdes, blockType: 'table_row' },
  { kind: 'table_cell', fixture: neuralOdes, blockType: 'table_cell' },
  { kind: 'algorithm', fixture: neuralOdes, blockType: 'algorithm' },
  { kind: 'citation', fixture: CITATION_FIXTURE, blockType: 'citation' },
];

describe('anchoring/targets.spec — all ten target kinds resolve', () => {
  for (const testCase of CASES) {
    it(`${testCase.kind} resolves against the same parse`, () => {
      const doc = indexDocument(testCase.fixture, 'targets');
      const block = firstOfType(doc, testCase.blockType);
      const anchor = captureAnchor({
        doc,
        blockId: block.id,
        targetKind: testCase.kind,
        ...(testCase.range === undefined
          ? {}
          : { startOffset: testCase.range[0], endOffset: testCase.range[1] }),
        ...(testCase.subTarget === undefined ? {} : { subTarget: testCase.subTarget }),
        id: `target-${testCase.kind}`,
        at: '2026-07-30T00:00:00Z',
        client: 'test',
      });

      const resolution = resolveAnchor(anchor, doc);

      expect(resolution.state).toBe('anchored');
      expect(resolution.blockIds).toContain(block.id);
      // Every kind but `guided_para` must produce paintable geometry. A resolution the reader
      // cannot draw is not a resolution.
      expect(resolution.polygons.length).toBeGreaterThan(0);
    });
  }

  it('guided_para resolves with NO geometry, and that is correct', () => {
    // A Guided paragraph is derived prose. It has no place on the page, so the geometry tiers are
    // skipped rather than faked — inventing a region for AI-written text would put derived content
    // on the paper, which is the one thing the provenance rules forbid outright.
    const doc = indexDocument(resnet, 'targets');
    const block = doc.blocks.find((b) => b.type === 'paragraph' && b.textCodePoints.length > 200);
    if (block === undefined) throw new Error('no paragraph');
    const anchor = captureAnchor({
      doc,
      blockId: block.id,
      startOffset: 0,
      endOffset: 60,
      targetKind: 'guided_para',
      provenanceClass: 'ai_generated',
      id: 'target-guided',
      at: '2026-07-30T00:00:00Z',
      client: 'test',
    });

    expect(anchor.provenanceClass).toBe('ai_generated');
    const resolution = resolveAnchor(anchor, doc);
    expect(resolution.state).toBe('anchored');
  });

  it('a table CELL resolves to the cell, not to its row or its table', () => {
    // Nested blocks all overlap the same quad — a cell is inside its row is inside its table — so a
    // naive geometric hit returns the table when the user pointed at one cell. The resolver drops
    // ancestors; this is the test that says so.
    const doc = indexDocument(neuralOdes, 'targets');
    const cell = firstOfType(doc, 'table_cell');
    const anchor = captureAnchor({
      doc,
      blockId: cell.id,
      targetKind: 'table_cell',
      subTarget: { kind: 'table_cell' },
      id: 'cell',
      at: 'x',
      client: 't',
    });
    const resolution = resolveAnchor(anchor, doc);
    expect(resolution.blockIds).toEqual([cell.id]);
  });

  it('the citation fixture carries a cites relation and a resolvable reference_entry', () => {
    const doc = indexDocument(CITATION_FIXTURE, 'targets');
    const citation = firstOfType(doc, 'citation');
    const entry = firstOfType(doc, 'reference_entry');

    // A citation anchor is TWO-ENDED: the callout plus the entry it resolves to. Both ends must
    // anchor independently, or "jump to the reference" is a dead link.
    for (const block of [citation, entry]) {
      const anchor = captureAnchor({
        doc,
        blockId: block.id,
        targetKind: 'citation',
        id: `cite-${block.id}`,
        at: 'x',
        client: 't',
      });
      const resolution = resolveAnchor(anchor, doc);
      expect(resolution.state).toBe('anchored');
      expect(resolution.tier).toBeLessThanOrEqual(Tier.Quote);
    }
  });

  it('part of an equation is a STRICT sub-region of the whole equation', () => {
    // The failure this guards: a sub-target that quietly falls back to the parent's full bbox looks
    // like it works — it resolves, it paints, it is in the right area — and silently loses the
    // "part of" entirely. Comparing areas is what catches it.
    const doc = indexDocument(attention, 'targets');
    const equation = firstOfType(doc, 'equation');
    const whole = captureAnchor({
      doc,
      blockId: equation.id,
      targetKind: 'equation',
      id: 'eq-whole',
      at: 'x',
      client: 't',
    });
    const part = captureAnchor({
      doc,
      blockId: equation.id,
      targetKind: 'equation_part',
      subTarget: { kind: 'equation_part', normalisedRect: [0, 0, 0.34, 1] },
      id: 'eq-part',
      at: 'x',
      client: 't',
    });

    const wq = firstQuad(whole);
    const pq = firstQuad(part);
    const areaW = (wq[2]! - wq[0]!) * (wq[3]! - wq[1]!);
    const areaP = (pq[2]! - pq[0]!) * (pq[3]! - pq[1]!);

    expect(areaP).toBeLessThan(areaW);
    expect(areaP / areaW).toBeCloseTo(0.34, 1);
    // …and it must sit INSIDE the parent, not merely be smaller.
    expect(pq[0]).toBeGreaterThanOrEqual(wq[0]! - 1e-9);
    expect(pq[2]).toBeLessThanOrEqual(wq[2]! + 1e-9);
  });
});
