"""papertree_document_ir - the PaperIR canonical document representation (Python twin).

The JSON Schema in ``packages/document-ir/schema/`` is the single source of truth (DESIGN.md §1).
Everything re-exported here is GENERATED from it by ``codegen/generate.ts``; nothing under
``generated/`` may be hand-edited, and ``test/codegen-drift.spec.ts`` fails the build if it is.

Two schema files, two generated modules (DESIGN.md §6): ``generated.models`` for PaperIR and
``generated.derivation_models`` for Derivation. They are deliberately not merged.

Validate a document with ``Paper.model_validate(loads(text))``. The models are strict on purpose -
see ``generated.models._Model`` for why lax coercion would make this binding disagree with ajv -
and ``loads`` is here rather than ``json.loads`` for the reason given on it.
"""

from typing import Any

from papertree_document_ir.canonical import (
    MAX_SAFE_JSON_INTEGER,
    CanonicalJsonError,
    canonical_json,
    canonical_json_for_determinism,
    ecmascript_number_to_string,
)
from papertree_document_ir.generated.derivation_models import (
    KNOWN_DERIVATION_KINDS,
    Derivation,
    DerivationKind,
    DerivationRoot,
    KnownDerivationKind,
    ModelAuthor,
    is_known_derivation_kind,
)
from papertree_document_ir.generated.models import (
    KNOWN_BLOCK_TYPES,
    KNOWN_HEADING_BLOCK_TYPES,
    KNOWN_RELATION_TYPES,
    MAX_PAYLOAD_DEPTH,
    MODEL_AUTHORSHIP_KEYS,
    AbstractRef,
    AlgoPrefixedHash,
    Alternative,
    BBox,
    Block,
    BlockId,
    BlockType,
    Confidence,
    DetectedLabel,
    DocumentConfidence,
    EquationPayload,
    EquationSymbol,
    FigurePanel,
    FigurePayload,
    Flow,
    Flows,
    ImageRef,
    KnownBlockType,
    KnownHeadingBlockType,
    KnownRelationType,
    Metadata,
    MetadataValue,
    MetadataYear,
    OpaquePayload,
    Page,
    PageId,
    Paper,
    PaperId,
    PaperRoot,
    PaperStatus,
    ParserInfo,
    Point,
    Polygon,
    Provenance,
    Reference,
    Relation,
    RelationType,
    Repair,
    RepairKind,
    Section,
    Sha256Hash,
    SourceKind,
    Span,
    TableCell,
    TableGrid,
    TablePayload,
    assert_model_free,
    find_excessive_depth,
    find_model_declaration,
    is_known_block_type,
    is_known_heading_block_type,
    is_known_relation_type,
    validate_opaque_payload,
)
from papertree_document_ir.geometry import (
    BBOX_EXTENT_EPSILON_PT,
    DEFAULT_LINE_GAP_PT,
    DEFAULT_LINE_OVERLAP_PT,
    ROTATIONS,
    GeometryError,
    PageFrame,
    RawPageBoxes,
    Rotation,
    Viewport,
    bbox_from_viewport,
    bbox_matches_polygon_extent,
    bbox_to_polygon,
    bbox_to_viewport,
    bboxes_intersect,
    denormalise_point,
    normalise_page_frame,
    normalise_point,
    normalise_polygon,
    normalise_rect,
    normalise_rotation,
    pdf_to_viewport,
    point_in_polygon,
    polygon_area,
    polygon_extent,
    polygon_is_simple,
    polygon_signed_area,
    polygons_intersect,
    rotation_swaps_axes,
    strip_user_unit,
    union_of_line_rects,
    viewport_scale,
    viewport_size,
    viewport_to_pdf,
)

# ─── identity, geometry and the semantic validator (F0.4) ───────────────────
#
# Hand-written, not generated, and each is the twin of a TypeScript module checked against the
# same committed conformance file rather than against the other language -
# ``conformance/identity-vectors.json`` (ADR-001 Amendment 1) and ``geometry-vectors.json``.
#
# ``validate`` carries the invariants JSON Schema cannot express. A document that passes the
# Pydantic models is well-FORMED; one that also passes ``validate_paper`` is well-formed and
# internally CONSISTENT. Fixtures must pass both.
from papertree_document_ir.identity import (
    BLOCK_ID_FORMULA_VERSION,
    BLOCK_ID_PATTERN,
    CASE_FOLD_MAP,
    CASE_FOLD_UNICODE_VERSION,
    CONTENT_HASH_ALGORITHM,
    GRID_PT,
    ID_BASE32_CHARS,
    LIGATURE_TABLE,
    MAX_QUANTISED_BUCKET,
    NFC_POST_PIN_DECOMPOSITIONS,
    NFC_POST_PIN_STARTERS,
    TEXT_PREFIX_CODEPOINTS,
    WHITESPACE_CODE_POINTS,
    AppliedProposal,
    BlockIdInput,
    BlockIdParts,
    BlockLike,
    RepairLike,
    RepairSkipReason,
    ResolvedText,
    SkippedProposal,
    block_id,
    block_id_parts,
    content_hash,
    content_hash_of_normalised,
    normalise_text,
    pinned_nfc,
    quantise,
    resolved_text,
    truncate_code_points,
)
from papertree_document_ir.validate import (
    SEMANTIC_RULES,
    Diagnostic,
    RuleInfo,
    SemanticValidationError,
    Severity,
    ValidateOptions,
    ValidationReport,
    assert_valid_paper,
    format_diagnostics,
    validate_paper,
)


def _reject_json_constant(token: str) -> Any:
    raise ValueError(f"{token} is not JSON and cannot cross the TypeScript boundary")


def loads(text: str | bytes) -> Any:
    """``json.loads`` with the non-JSON constants switched off.

    CPython accepts ``NaN``, ``Infinity`` and ``-Infinity`` as number literals; ``JSON.parse``
    cannot read them at all, so a document containing one is a document the two halves of this
    system cannot agree on - Python would hand Pydantic a float and TypeScript would throw at the
    parse layer, before any validator got a verdict. Every float in PaperIR 1.0.0 is bounded, so
    nothing is accepted today that this rejects; it is here so the first UNBOUNDED number added in
    a later version does not open the hole silently. See DESIGN.md §12.7.
    """
    import json

    return json.loads(text, parse_constant=_reject_json_constant)


__all__ = [
    "ecmascript_number_to_string",
    "canonical_json_for_determinism",
    "canonical_json",
    "CanonicalJsonError",
    "MAX_SAFE_JSON_INTEGER",
    "AbstractRef",
    "AlgoPrefixedHash",
    "Alternative",
    "AppliedProposal",
    "BBOX_EXTENT_EPSILON_PT",
    "BBox",
    "BLOCK_ID_FORMULA_VERSION",
    "BLOCK_ID_PATTERN",
    "Block",
    "BlockId",
    "BlockIdInput",
    "BlockIdParts",
    "BlockLike",
    "BlockType",
    "CASE_FOLD_MAP",
    "CASE_FOLD_UNICODE_VERSION",
    "CONTENT_HASH_ALGORITHM",
    "Confidence",
    "DEFAULT_LINE_GAP_PT",
    "DEFAULT_LINE_OVERLAP_PT",
    "Derivation",
    "DerivationKind",
    "DerivationRoot",
    "DetectedLabel",
    "Diagnostic",
    "DocumentConfidence",
    "EquationPayload",
    "EquationSymbol",
    "FigurePanel",
    "FigurePayload",
    "Flow",
    "Flows",
    "GRID_PT",
    "GeometryError",
    "ID_BASE32_CHARS",
    "ImageRef",
    "KNOWN_BLOCK_TYPES",
    "KNOWN_DERIVATION_KINDS",
    "KNOWN_HEADING_BLOCK_TYPES",
    "KNOWN_RELATION_TYPES",
    "KnownBlockType",
    "KnownDerivationKind",
    "KnownHeadingBlockType",
    "KnownRelationType",
    "LIGATURE_TABLE",
    "MAX_PAYLOAD_DEPTH",
    "MAX_QUANTISED_BUCKET",
    "MODEL_AUTHORSHIP_KEYS",
    "Metadata",
    "MetadataValue",
    "MetadataYear",
    "ModelAuthor",
    "NFC_POST_PIN_DECOMPOSITIONS",
    "NFC_POST_PIN_STARTERS",
    "OpaquePayload",
    "Page",
    "PageFrame",
    "PageId",
    "Paper",
    "PaperId",
    "PaperRoot",
    "PaperStatus",
    "ParserInfo",
    "Point",
    "Polygon",
    "Provenance",
    "ROTATIONS",
    "RawPageBoxes",
    "Reference",
    "Relation",
    "RelationType",
    "Repair",
    "RepairKind",
    "RepairLike",
    "RepairSkipReason",
    "ResolvedText",
    "Rotation",
    "RuleInfo",
    "SEMANTIC_RULES",
    "Section",
    "SemanticValidationError",
    "Severity",
    "Sha256Hash",
    "SkippedProposal",
    "SourceKind",
    "Span",
    "TEXT_PREFIX_CODEPOINTS",
    "TableCell",
    "TableGrid",
    "TablePayload",
    "ValidateOptions",
    "ValidationReport",
    "Viewport",
    "WHITESPACE_CODE_POINTS",
    "assert_model_free",
    "assert_valid_paper",
    "bbox_from_viewport",
    "bbox_matches_polygon_extent",
    "bbox_to_polygon",
    "bbox_to_viewport",
    "bboxes_intersect",
    "block_id",
    "block_id_parts",
    "content_hash",
    "content_hash_of_normalised",
    "denormalise_point",
    "find_excessive_depth",
    "find_model_declaration",
    "format_diagnostics",
    "is_known_block_type",
    "is_known_derivation_kind",
    "is_known_heading_block_type",
    "is_known_relation_type",
    "loads",
    "normalise_page_frame",
    "normalise_point",
    "normalise_polygon",
    "normalise_rect",
    "normalise_rotation",
    "normalise_text",
    "pinned_nfc",
    "pdf_to_viewport",
    "point_in_polygon",
    "polygon_area",
    "polygon_extent",
    "polygon_is_simple",
    "polygon_signed_area",
    "polygons_intersect",
    "quantise",
    "resolved_text",
    "rotation_swaps_axes",
    "strip_user_unit",
    "truncate_code_points",
    "union_of_line_rects",
    "validate_opaque_payload",
    "validate_paper",
    "viewport_scale",
    "viewport_size",
    "viewport_to_pdf",
]
